In [1]:
import pandas as pd
import numpy as np
file = pd.read_csv('Cleaned.csv')
df = pd.DataFrame(file)

In [2]:
df.head()

county  propertyType  bedrooms  bathrooms  squareFootage  lotSize  \
0      10             1         2        1.0            862     4792   
1      56             1         3        1.0           1750     4792   
2      20             1         5        4.0           3000    21780   
3      48             1         3        2.5           4448    11326   
4      48             1         3        2.0           1050     4792   

   yearBuilt   price  
0       1941  360000  
1       1941  314999  
2       2021  540000  
3       2024  777400  
4       1998  379900

In [3]:
df.keys()

Index(['county', 'propertyType', 'bedrooms', 'bathrooms', 'squareFootage',
       'lotSize', 'yearBuilt', 'price'],
      dtype='object')

In [4]:
df['propertyType'].unique()

array([1, 2, 0], dtype=int64)

In [13]:
columns_to_drop = ['id', 'formattedAddress', 'addressLine1', 'addressLine2', 'city',
       'state', 'zipCode', 'latitude', 'longitude', 'listedDate', 'removedDate', 'createdDate', 'daysOnMarket', 'lastSeenDate', 'status']
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]
dropped = df.drop(columns=existing_columns_to_drop)

In [9]:
# if dropped['propertyType'] == ['Apartment','Manufactured',
#        'Multi-Family','Land', 'nan', '2.0', '3.0', '5.0', '7.0',
#        '6.0', '4.0', '0.0', '10.0', '1.0', '8.0', '12.0']:
    

In [14]:
my_conditions = ['Apartment','Manufactured',
       'Multi-Family','Land', 'nan', '2.0', '3.0', '5.0', '7.0',
       '6.0', '4.0', '0.0', '10.0', '1.0', '8.0', '12.0', 'Inactive']

In [15]:
dropped_cleaned = dropped[~dropped['propertyType'].isin(my_conditions)]
dropped_cleaned = dropped_cleaned[dropped_cleaned["lotSize"] != "Inactive"]
dropped_cleaned = dropped_cleaned[dropped_cleaned["squareFootage"] != "Inactive"]
dropped_cleaned = dropped_cleaned[dropped_cleaned["bedrooms"] != "Inactive"]
dropped_cleaned = dropped_cleaned[dropped_cleaned["bathrooms"] != "Inactive"]
dropped_cleaned["lotSize"] = dropped_cleaned["lotSize"].astype(str)


dropped_cleaned = dropped_cleaned[dropped_cleaned["lotSize"].str.len().between(0, 8)]
dropped_cleaned = dropped_cleaned.dropna()
dropped_cleaned

county  propertyType  bedrooms  bathrooms  squareFootage lotSize  \
0          10             1         2        1.0            862    4792   
1          56             1         3        1.0           1750    4792   
2          20             1         5        4.0           3000   21780   
3          48             1         3        2.5           4448   11326   
4          48             1         3        2.0           1050    4792   
...       ...           ...       ...        ...            ...     ...   
56500       5             1         4        3.0           2646   25265   
56501      47             1         3        2.0           2028   19166   
56502      47             1         4        2.0           1620   10454   
56503      13             1         7        3.0           3194   16988   
56504      21             0         2        2.0           1037    2178   

       yearBuilt   price  
0           1941  360000  
1           1941  314999  
2           2021  540000  
3           2024  777400  
4           1998  379900  
...          ...     ...  
56500       2020  650000  
56501       2008  349000  
56502       2008  240000  
56503       2010  539999  
56504       1985  255000  

[56505 rows x 8 columns]

In [16]:
dropped_cleaned['propertyType'].unique()

array([1, 2, 0], dtype=int64)

In [17]:
#Bedrooms more than 10
#Bathrooms more than 8 and half
#Square feet more than 20000
#year built greater than 2024 get rid of it
#price under 15K



In [18]:
dropped_cleaned['propertyType'].unique()


array([1, 2, 0], dtype=int64)

In [19]:
dropped_cleaned['county'].unique()


array([10, 56, 20, 48, 34, 52, 42, 44,  0,  4, 50, 24,  2, 46, 32,  6, 22,
       12, 18, 26, 40, 36, 54, 28, 14, 16, 38, 30,  8, 49, 21,  7, 35,  5,
       57, 11, 53, 41, 45, 43,  1, 31, 51, 19, 15,  3, 47, 27, 39, 13, 17,
       33, 25, 55, 23, 29, 37,  9], dtype=int64)

In [20]:
#dropped_cleaned = pd.DataFrame(data)
dropped_cleaned["bedrooms"] = pd.to_numeric(dropped_cleaned["bedrooms"], errors='coerce').fillna(0).astype(int)
dropped_cleaned["squareFootage"] = pd.to_numeric(dropped_cleaned["squareFootage"], errors='coerce').fillna(0).astype(int)
dropped_cleaned["lotSize"] = pd.to_numeric(dropped_cleaned["lotSize"], errors='coerce').fillna(0).astype(int)
dropped_cleaned["yearBuilt"] = pd.to_numeric(dropped_cleaned["yearBuilt"], errors='coerce').fillna(0).astype(int)
dropped_cleaned["price"] = pd.to_numeric(dropped_cleaned["price"], errors='coerce').fillna(0).astype(int)
dropped_cleaned['bathrooms'] = dropped_cleaned['bathrooms'].astype(float)


In [21]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
dropped_cleaned['county'] = encoder.fit_transform(dropped_cleaned['county'])
encoder = LabelEncoder()
dropped_cleaned['propertyType'] = encoder.fit_transform(dropped_cleaned['propertyType'])

In [22]:
print(dropped_cleaned)


       county  propertyType  bedrooms  bathrooms  squareFootage  lotSize  \
0          10             1         2        1.0            862     4792   
1          56             1         3        1.0           1750     4792   
2          20             1         5        4.0           3000    21780   
3          48             1         3        2.5           4448    11326   
4          48             1         3        2.0           1050     4792   
...       ...           ...       ...        ...            ...      ...   
56500       5             1         4        3.0           2646    25265   
56501      47             1         3        2.0           2028    19166   
56502      47             1         4        2.0           1620    10454   
56503      13             1         7        3.0           3194    16988   
56504      21             0         2        2.0           1037     2178   

       yearBuilt   price  
0           1941  360000  
1           1941  314999  
2     

In [23]:
dropped_cleaned.dtypes


county             int64
propertyType       int64
bedrooms           int32
bathrooms        float64
squareFootage      int32
lotSize            int32
yearBuilt          int32
price              int32
dtype: object

In [104]:
dropped_cleaned.to_csv('output.csv', index=False)

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load the cleaned dataset
dropped_cleaned.to_csv('dropped_cleaned.csv', index=False)
filtered_data = pd.read_csv('dropped_cleaned.csv')

# Check for non-numeric columns
print(filtered_data.dtypes)

# Convert categorical variables to numeric using one-hot encoding
filtered_data = pd.get_dummies(filtered_data, drop_first=True)

# Define the features and target variable
X = filtered_data.drop(columns=['price'])  # Features
y = filtered_data['price']                   # Target variable

# Drop rows with missing target values
X = X[~y.isna()]
y = y.dropna()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest Regressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

# Optionally, you can print feature importances
importances = model.feature_importances_
feature_importances = pd.DataFrame(importances, index=X.columns, columns=['Importance']).sort_values('Importance', ascending=False)
print(feature_importances)

county             int64
propertyType       int64
bedrooms           int64
bathrooms        float64
squareFootage      int64
lotSize            int64
yearBuilt          int64
price              int64
dtype: object
Mean Squared Error: 182145746191.93063
R^2 Score: 0.748165884827935
               Importance
squareFootage    0.505420
county           0.150578
lotSize          0.132106
yearBuilt        0.108187
bathrooms        0.056824
bedrooms         0.034776
propertyType     0.012109


In [27]:

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Step 1: Load the Data
data = pd.read_csv('cleaned_file.csv')  # Replace with your actual file path

# Step 2: Explore the Data
print(data.head())
print(data.info())
print(data.describe())

# Step 3: Handle Missing Values
# Check for missing values
print(data.isnull().sum())
# Fill missing values (example: forward fill)
#data.fillna(method='ffill', inplace=True)

# Step 4: Feature Selection
# Define features (X) and target variable (y)
X = data[['county', 'propertyType', 'bedrooms', 'bathrooms', 'squareFootage']]  # Replace with actual feature names
y = data['price']  # Replace with the actual target variable name

# Step 5: Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 7: Model Selection
model = LinearRegression()

# Step 8: Model Training
model.fit(X_train, y_train)

# Step 9: Model Prediction
y_pred = model.predict(X_test)

# Step 10: Model Evaluation
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

# Optional: Hyperparameter Tuning (if needed)
# from sklearn.model_selection import GridSearchCV
# param_grid = {'fit_intercept': [True, False]}
# grid_search = GridSearchCV(LinearRegression(), param_grid, cv=5)
# grid_search.fit(X_train, y_train)
# print("Best parameters:", grid_search.best_params_)

# Optional: Save the model (if needed)
# import joblib
# joblib.dump(model, 'linear_regression_model.pkl')

# Optional: Load the model (if needed)
# model = joblib.load('linear_regression_model.pkl')

  county   propertyType  bedrooms  bathrooms  squareFootage  lotSize  \
0  Davis  Single Family       2.0        1.0          862.0   4792.0   
1  Weber  Single Family       3.0        1.0         1750.0   4792.0   
2   Iron  Single Family       5.0        4.0         3000.0  21780.0   
3   Utah  Single Family       3.0        2.5         4448.0  11326.0   
4   Utah  Single Family       3.0        2.0         1050.0   4792.0   

   yearBuilt     price  
0     1941.0  360000.0  
1     1941.0  314999.0  
2     2021.0  540000.0  
3     2024.0  777400.0  
4     1998.0  379900.0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58208 entries, 0 to 58207
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   county         58208 non-null  object 
 1   propertyType   58208 non-null  object 
 2   bedrooms       58208 non-null  float64
 3   bathrooms      58208 non-null  float64
 4   squareFootage  58208 non-null  float64
 

ValueError: could not convert string to float: 'Cache'

In [26]:
dropped_cleaned.dtypes

county             int64
propertyType       int64
bedrooms           int32
bathrooms        float64
squareFootage      int32
lotSize            int32
yearBuilt          int32
price              int32
dtype: object

In [109]:
from sklearn.linear_model import LinearRegression

model1 = LinearRegression()
model1.fit(X_train, y_train)

ValueError: could not convert string to float: 'Cache'

In [110]:
%pip install xgboost
import xgboost as xgb

# Convert categorical variables to numeric using one-hot encoding
X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, drop_first=True)

# Align the train and test dataframes by the columns
X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

# Ensure y_train does not contain NaN, infinity, or excessively large values
y_train_cleaned = y_train.replace([np.inf, -np.inf], np.nan).dropna()

# Align X_train_encoded with y_train_cleaned
X_train_encoded = X_train_encoded.loc[y_train_cleaned.index]

# Ensure y_train_cleaned is 1-dimensional
y_train_cleaned = y_train_cleaned.values.ravel()

model2 = xgb.XGBRegressor()
model2.fit(X_train_encoded, y_train_cleaned)

Note: you may need to restart the kernel to use updated packages.


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [111]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Example data
# X = features, y = target variable
X = np.random.rand(100, 5)  # 100 samples, 5 features
y = np.random.rand(100)      # 100 target values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and fit the model
model11 = KNeighborsRegressor(n_neighbors=5)
model11.fit(X_train, y_train)

# Make predictions
predictions = model11.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')


Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [112]:
from sklearn.linear_model import Ridge

model3 = Ridge(alpha=1.0)
model3.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [113]:
from sklearn.linear_model import Lasso

model4 = Lasso(alpha=0.1)
model4.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [114]:
from sklearn.linear_model import ElasticNet

model5 = ElasticNet(alpha=0.1, l1_ratio=0.5)
model5.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [115]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly_features = PolynomialFeatures(degree=2)
X_poly = poly_features.fit_transform(X_train)

model6 = LinearRegression()
model6.fit(X_poly, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [117]:
from sklearn.tree import DecisionTreeRegressor

model7 = DecisionTreeRegressor()
model7.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [118]:
from sklearn.ensemble import RandomForestRegressor

model8 = RandomForestRegressor(n_estimators=100)
model8.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [119]:
from sklearn.svm import SVR

model9 = SVR(kernel='rbf')
model9.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [120]:
from sklearn.ensemble import GradientBoostingRegressor

model10 = GradientBoostingRegressor()
model10.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [121]:
from sklearn.neighbors import KNeighborsRegressor

model11 = KNeighborsRegressor(n_neighbors=5)
model11.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [122]:
from sklearn.linear_model import BayesianRidge

model12 = BayesianRidge()
model12.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.08431426685901196
R-squared: -0.11657821242859057


In [123]:
%pip install catboost
from catboost import CatBoostRegressor

model13 = CatBoostRegressor(iterations=100, learning_rate=0.1, depth=6)
model13.fit(X_train, y_train)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Note: you may need to restart the kernel to use updated packages.
0:	learn: 0.2631153	total: 1.14ms	remaining: 113ms
1:	learn: 0.2592497	total: 2.21ms	remaining: 108ms
2:	learn: 0.2547992	total: 9.86ms	remaining: 319ms
3:	learn: 0.2508859	total: 11.9ms	remaining: 286ms
4:	learn: 0.2481340	total: 14.4ms	remaining: 274ms
5:	learn: 0.2444337	total: 15.3ms	remaining: 239ms
6:	learn: 0.2393482	total: 16.4ms	remaining: 217ms
7:	learn: 0.2357519	total: 17.9ms	remaining: 206ms
8:	learn: 0.2339561	total: 19ms	remaining: 192ms
9:	learn: 0.2301234	total: 19.8ms	remaining: 178ms
10:	learn: 0.2256535	total: 23.2ms	remaining: 188ms
11:	learn: 0.2231054	total: 24.5ms	remaining: 180ms
12:	learn: 0.2180124	total: 25.4ms	remaining: 170ms
13:	learn: 0.2161112	total: 26.1ms	remaining: 160ms
14:	learn: 0.2136554	total: 26.8ms	remaining: 152ms
15:	learn: 0.2103828	total: 27.5ms	remaining: 145ms
16:	learn: 0.2073222	total: 28.2ms	remaining: 138ms
17:	learn: 0.2041383	total: 29.3ms	remaining: 134ms
18:	learn: